@extends('mastermain')

@section('cont')
<h1 class="indent-lg">Government Data Request Principles</h1>
<p class="indent-lg">We understand that, when you entrust us with your digital life, you expect us to keep your stuff safe. Like most online services, we sometimes receive requests from governments seeking information about our users. These principles describe how we deal with the requests we receive and how we’ll work to try and change the laws to make them more protective of your privacy.</p>
<p><strong>Be transparent:</strong>  Online services should be allowed to report the exact number of government data requests received, the number of accounts affected by those requests and the laws used to justify the requests. We’ll continue to advocate for the right to provide this important information.</p>
<p class="indent-lg">Our Transparency Report discloses the number of law enforcement requests we receive and the number of accounts affected. Currently, our report doesn’t include specific details about the number of national security requests we receive from the US government, if any. We’ve urged the courts and the government to allow services such as Dropbox to disclose the precise number of national security requests they receive and the number of accounts affected. We’ll continue this fight. In the meantime, we’re providing as much information about national security requests received and accounts affected as we're allowed to.</p>
<p><strong>Fight blanket requests:</strong>  Government data requests should be limited to specific people and investigations. We’ll resist requests directed to large groups of people or that seek information unrelated to a specific investigation.</p>
<p class="indent-lg">The US government has been seeking phone records from telecommunications companies relating to large groups of users without suspicion that those users have been involved in illegal activity. We don’t think this is legal and will resist requests that seek information relating to large groups of users or that don’t relate to specific investigations.</p>
<p><strong>Protect all users:</strong>  Laws authorising governments to request user data from online services shouldn’t treat people differently based on their citizenship or where they live. We’ll work hard to reform these laws.</p>
<p class="indent-lg">Certain laws give people different protection based on where they live or their citizenship. These laws don’t reflect the global nature of online services. We’re committed to extending fundamental privacy protections to all users: government data requests shouldn’t be in bulk, they should relate to specific individuals and investigations, and a neutral third party should evaluate and sign off requests for content before they're issued.</p>
<p><strong>Provide trusted services:</strong>  Governments should never install backdoors into online services or compromise infrastructure to obtain user data. We’ll continue to work to protect our systems and to change laws to make it clear that this type of activity is illegal.</p>
<p>There have been reports that governments have been tapping into data centre traffic of other services. We don’t believe this is right. Governments should instead request user data by contacting online services directly and presenting legal process. This allows services to scrutinise the data requests and resist where appropriate.</p>

@endsection